from .secrets import INSIGHTVM_BASE_URL, INSIGHTVM_USERNAME, INSIGHTVM_PASSWORD

# Add to your settings
INSIGHTVM_CONFIG = {
    'BASE_URL': INSIGHTVM_BASE_URL,
    'USERNAME': INSIGHTVM_USERNAME,
    'PASSWORD': INSIGHTVM_PASSWORD
}
